### ISSUE TITLE
Parabolic -- Shiny implementation

### ISSUE THREAD

**Issue by ngreen-gt** [pakinja/Data-R-Value#2]
Hi @pakinja,

I've implemented the parabolic code, which I saw on R-blogger, as a Shiny app for fun, so I want to share with you.  The source is on [my Github](http://www.github.com/ngreen-gt/parabolic).  I've only run the app locally through RStudio and it was working ok.  

I may add additional parameters (like starting height) and would be interested in adding air resistance to the model.  I've made small changes like using alpha instead of alfa and changing to from meters to feet.  

Right now I help with a high school robotics team and they have a challenge shooting a ball, so I thought a Shiny app along with the parabolic code might be a useful exercise to introduce them to the physics of trajectory motion.  

Cheers, @ngreen-gt

**Comment by pakinja** [comment]
Hi @ngreen-gt 
Thank you very much for sharing your application with me. I really wanted to do the simulation in an interactive way but I have not used much the Shiny package, so your application will help me a lot to learn it. Soon I will be making the model with air resistance and hope it will also be useful for you.
I am a physics professor, so hopefully we can collaborate in the future.
Greetings, @pakinja
